#!/bin/bash

set -euo pipefail

readonly dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

pushd "${dir}/../"
trap 'popd' EXIT

# Add workder nodes
# Steps at https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/

for i in {0..2}; do
cat <<EOF | vagrant ssh "worker-${i}" -- sudo bash
echo "Initializing worker node ${i}"
apt-get update
apt-get install -y sshpass
apt-get install -y socat libgpgme11 nfs-common

sshpass -p "vagrant" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null vagrant@master-0:/home/vagrant/worker_join_command.sh .
sh ./worker_join_command.sh
EOF
done