#!/bin/bash

set -euo pipefail

readonly dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

pushd "${dir}/../"
trap 'popd' EXIT

# ./scripts/distclean
vagrant up

./scripts/setup-master
./scripts/setup-worker
./scripts/setup-traefik

echo "192.168.199.40 api.k8s.virtualbox" | sudo tee -a /etc/hosts
echo -e "\033[1mFinished. Cluster should be healthy and soon in state ready:\033[0m"
echo -e "\033[1mapi.k8s.virtualbox is load balancer of masters\033[0m"