#!/bin/bash

set -euo pipefail

readonly dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

pushd "${dir}/../"
trap 'popd' EXIT

# ./scripts/distclean
# ./scripts/download-packages

# This does not work correctly on OSX, CA:true has to be sepcified in config file instead of -extensions
# because openssl utility on OSX doesn't support -extensions well. 
# ./scripts/generate-ca-certs  

vagrant up
./scripts/check-etcd
./scripts/setup-master
./scripts/setup-worker
./scripts/setup-traefik
./scripts/check-cluster
./scripts/smoke-test